/// Flutter icons MyFlutterApp
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/DownloadedIcons.ttf
///
///
/// * RPG Awesome, Copyright (c) 2014, Daniela Howe
///         Author:    Daniela Howe & Ivan Montiel
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://nagoshiashumari.github.io/Rpg-Awesome/
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class DownloadedIcons {
  DownloadedIcons._();

  static const _kFontFam = 'DownloadedIcons';
  static const _kFontPkg = null;

  static const IconData hospital_cross = IconData(0xea07, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pill = IconData(0xea60, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pills_1 = IconData(0xea61, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData syringe_1 = IconData(0xeac2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData file_medical = IconData(0xf477, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData first_aid = IconData(0xf479, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hospital_symbol = IconData(0xf47e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notes_medical = IconData(0xf481, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pills = IconData(0xf484, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData prescription_bottle = IconData(0xf485, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData prescription_bottle_alt = IconData(0xf486, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData syringe = IconData(0xf48e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tablets = IconData(0xf490, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData thermometer = IconData(0xf491, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wind = IconData(0xf72e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}